homework27
OleksiiFltv/PlayWright-test pull request #6
Opened 2024-08-15 10:53 UTC by OleksiiFltv

2024-08-15 18:45 UTC, sttaran requested changes

2024-08-15 18:45 UTC, sttaran commented on tests/mockProfile.spec.js
> +  const textContent = await profileName.textContent();
remove it

2024-08-15 18:45 UTC, sttaran commented on tests/mockProfile.spec.js
> +  expect(textContent).toContain("Andrew MockedUser");
use https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-have-text

2024-08-15 18:45 UTC, sttaran commented on tests/mockProfile.spec.js
> +  const profileName = await page.locator(".profile_name.display-4");
.profile_name would be enough

2024-08-15 18:45 UTC, sttaran commented on tests/mockProfile.spec.js
> +  expect(textContent).toContain("Andrew MockedUser");
reuse data from `modifiedResponse`

2024-08-16 09:42 UTC, OleksiiFltv commented
fixed

2024-08-16 14:52 UTC, sttaran approved these changes

2024-08-20 14:28 UTC, merged