Homework28
OleksiiFltv/PlayWright-test pull request #7
Opened 2024-08-15 14:52 UTC by OleksiiFltv

2024-08-15 15:11 UTC, OleksiiFltv commented
I forgot to remove the commented-out fields. Fixed it in time ))

2024-08-15 18:49 UTC, sttaran requested changes

2024-08-15 18:49 UTC, sttaran commented on tests/apiTests/addCarsApi.spec.js
> +      reportedAt: "2024-08-15",
this date should always refer to current day otherwise your test will fail

2024-08-15 18:49 UTC, sttaran commented on tests/apiTests/addCarsApi.spec.js
> +      carId: 185826,
create car this test 

do not rely on existing data

2024-08-16 08:29 UTC, OleksiiFltv commented
All fixed. please see the last commit

2024-08-16 09:20 UTC, sttaran approved these changes

2024-08-16 12:59 UTC, merged